In [ ]:
# filename = "3000728773-Schedule C - Pricing Attachment I.xls"   --- more than 15line of LONG des
# filename = "3000743525-Schedule C - Pricing Attachment I.xls"   ---- roman numbers4

In [ ]:
# # filename = "3000754591-Schedule C - Pricing Attachment I.xls"  ---- FOLDER AND SUB FOLDER SEQ ERROR

# 02.00 Surface Preparation',
# 04.00 Tank Painting Work',
# 05.00 Material Handling',
# 06.00 Welding and Miscellanneous Tank Repairs',
# 08.00 Sand / Cement',
# 09.00 Civil Works',
# 10.00 Pressure Grouting of Tank Bottoms',
# 11.00 Electrical Repair /Installation WORK',
# 12.00 Tank Testing and Inspection',
# 13.00 Remove Washwater, Sludges, Products or',
# ============================================
# 01.01 Blind & Spectacle
# 01.02 Cover & Manway
# 01.03 Manway Gasket
# 03.01 Solvent Cleanin

# 06.10 Seal Fabric and Rubber Seal Repairs',
# 06.11 Jack Knife & Drain',
# 06.12 Rolling Ladders',
# 06.13 Miscellaneous Works',
# 06.14 Install Air Foam System',
# 06.15 Raising and Lowering of Roof Support',
# 06.16 Grind/Remove Weld Cracks',
# 06.17 Perform Thermit Welding (Cadweld)',
# 06.18 Installation of Drip Plate',
# 06.19 Rim Vents',
# 06.20 Remove or Reinstall Main Inlet',
# 06.21 Hydrotest Valves, 150 lb.or more',
# 06.22 Cleaning Bolts and Others'}

# (^[0-9]{1,2}[.][1-9]{1,2})(\s|\S|)[a-zA-Z].+

In [ ]:

# filename = "3000764586-Schedule C - Pricing Attachment I.xls"


# 0: '00001 PAINTING AND COATING SERVICES',
# 01.00 Internal Surface Repair',
# 1.01 Saudi Aramco Supplied Materials',
# 1.02 Contractor supplied materials',
# 02.00 External Surface Prepration',
# 2.01 Saudi Aramco Supplied Materials',
# 2.02 Contractor supplied materials',
# 03.00 Internal Coating',
# 3.01 Saudi Aramco Supplied Materials',
# 3.02 Contractor supplied materials',
# 04.00 External Coating',
# 4.01 Saudi Aramco Supplied Materials',
# 4.02 Contractor supplied materials',
# 05.00 Non-APCS',
# 5.01 Primer Saudi Aramco Supplied Materials',
# 5.02 Top Coat Saudi Aramco Supplied aterials',
# 5.03 Payment by Contractor Supplly Parts Form',
# 06.00 Labor Rates',
# 07.00 Equipment Rate',
# 08.00 Surface Protection',
#  720: '09.00 Distance Premium',
#  726: '10.00 Others',
#  760: '11.00 Pipe Internal Blasting and Coating',
#  856: '12.00 Fiscal Measure'}

In [1]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [2]:
filename = "3000599798-Schedule C - Pricing Attachment I.xls"

In [3]:
# start = datetime.now()
df = pd.read_excel(filename)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,Vendor Name:,HCL ARABIA CO. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Vendor No:,10053811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RFQ Title:,IT Application Development & Implmnt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,RFQ No:,6000106938,Version:,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Requisition No:,3000599798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,END,NaN

In [4]:
df.dropna(how = 'all', axis = 0, inplace = True)
df.dropna(how = 'all', axis = 1, inplace = True)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 11
0,NaN,Vendor Name:,HCL ARABIA CO. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Vendor No:,10053811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RFQ Title:,IT Application Development & Implmnt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,RFQ No:,6000106938,Version:,0,NaN,NaN,NaN,NaN,NaN
4,NaN,Requisition No:,3000599798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
214,NaN,NaN,required Saudization level as per Attachment I...,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
216,NaN,NaN,6.0 Lump Sum Release PO,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
217,10,NaN,Lump Sum Price,NaN,PU,SAR,NaN,1,1,18302082.0
318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,END,NaN

In [5]:
# df.fillna('',inplace = True, axis = 0)
df.reset_index(drop = True, inplace = True)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 11
0,NaN,Vendor Name:,HCL ARABIA CO. LTD.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Vendor No:,10053811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RFQ Title:,IT Application Development & Implmnt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,RFQ No:,6000106938,Version:,0,NaN,NaN,NaN,NaN,NaN
4,NaN,Requisition No:,3000599798,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
213,NaN,NaN,required Saudization level as per Attachment I...,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
215,NaN,NaN,6.0 Lump Sum Release PO,NaN,NaN,NaN,NaN,NaN,BLANK,NaN
216,10,NaN,Lump Sum Price,NaN,PU,SAR,NaN,1,1,18302082.0
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,END,NaN

In [6]:
df4 = df.iloc[3:5,1:3]
df4

        Unnamed: 1  Unnamed: 2
3          RFQ No:  6000106938
4  Requisition No:  3000599798

In [7]:
df[7:10]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 11
7,NaN,Title:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Date:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Line\nItem,Service\nNumber,Description,Quantity,Unit,CUR,Unit Price,Per UOM,NaN,NaN

In [8]:
col = list(df.values[9][:7])
col

['Line\nItem',
 'Service\nNumber',
 'Description',
 'Quantity',
 'Unit',
 'CUR',
 'Unit Price']

In [9]:
# df.iloc[9:, :8]

In [10]:
col1 = []
for i in col:
    col1.append(re.sub(r'[\n\s]', '_', i))
col1

['Line_Item',
 'Service_Number',
 'Description',
 'Quantity',
 'Unit',
 'CUR',
 'Unit_Price']

In [11]:
df.iloc[9:10]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 11
9,Line\nItem,Service\nNumber,Description,Quantity,Unit,CUR,Unit Price,Per UOM,NaN,NaN

In [12]:
df1 = df.iloc[11:, :7]
df1.columns = col1
df1.reset_index(drop = True,inplace = True)
df1

,Line_Item,Service_Number,Description,Quantity,Unit,CUR,Unit_Price
0,NaN,NaN,00001 IT Application Development & Implmnt.,NaN,NaN,NaN,NaN
1,10,NaN,IT Application Development,NaN,PU,SAR,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,1.0 Time Unit Rates Release PO,NaN,NaN,NaN,NaN
4,NaN,NaN,1.1 Man-Hour Rates,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
202,NaN,NaN,required Saudization level as per Attachment I...,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,6.0 Lump Sum Release PO,NaN,NaN,NaN,NaN
205,10,NaN,Lump Sum Price,NaN,PU,SAR,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df1.dropna(how = 'all', axis = 0, inplace = True)
# df1.dropna(how = 'all', axis = 1, inplace = True)
df1.reset_index(drop = True,inplace = True)
df1

,Line_Item,Service_Number,Description,Quantity,Unit,CUR,Unit_Price
0,NaN,NaN,00001 IT Application Development & Implmnt.,NaN,NaN,NaN,NaN
1,10,NaN,IT Application Development,NaN,PU,SAR,NaN
2,NaN,NaN,1.0 Time Unit Rates Release PO,NaN,NaN,NaN,NaN
3,NaN,NaN,1.1 Man-Hour Rates,NaN,NaN,NaN,NaN
4,NaN,NaN,1.1.1 National Market,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
186,20,NaN,Deduction Per manhour,NaN,VAL,SAR,NaN
187,NaN,NaN,Deduction of SR100 for each Direct Labor manho...,NaN,NaN,NaN,NaN
188,NaN,NaN,required Saudization level as per Attachment I...,NaN,NaN,NaN,NaN
189,NaN,NaN,6.0 Lump Sum Release PO,NaN,NaN,NaN,NaN
190,10,NaN,Lump Sum Price,NaN,PU,SAR,NaN

In [14]:
pd.set_option('display.max_rows', None)
df1

,Line_Item,Service_Number,Description,Quantity,Unit,CUR,Unit_Price
0,NaN,NaN,00001 IT Application Development & Implmnt.,NaN,NaN,NaN,NaN
1,10,NaN,IT Application Development,NaN,PU,SAR,NaN
2,NaN,NaN,1.0 Time Unit Rates Release PO,NaN,NaN,NaN,NaN
3,NaN,NaN,1.1 Man-Hour Rates,NaN,NaN,NaN,NaN
4,NaN,NaN,1.1.1 National Market,NaN,NaN,NaN,NaN
5,10,NaN,Senior Project Manager,NaN,H,SAR,NaN
6,20,NaN,IT Consultant,NaN,H,SAR,NaN
7,30,NaN,Integration & Architecture Consultant I,NaN,H,SAR,NaN
8,40,NaN,Functional Analyst I,NaN,H,SAR,NaN
9,50,NaN,Applications Developer I,NaN,H,SAR,NaN
10,60,NaN,Project Manager,NaN,H,SAR,NaN
11,70,NaN,Integration & Architecture Consultant II,NaN,H,SAR,NaN
12,80,NaN,Functional Analyst II,NaN,H,SAR,NaN
13,90,NaN,Applications Developer II,NaN,H,SAR,NaN
14,100,NaN,Integration & Arc. Consultant III,NaN,H,SAR,NaN
15,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
16,110,NaN,Change Management Consultant,NaN,H,SAR,NaN
17,120,NaN,Functional Analyst III,NaN,H,SAR,NaN
18,130,NaN,Applications Developer III,NaN,H,SAR,NaN
19,140,NaN,Training Development and Delivery,NaN,H,SAR,NaN
20,150,NaN,Technical Writer,NaN,H,SAR,NaN
21,160,NaN,Functional Analyst IV,NaN,H,SAR,NaN
22,170,NaN,Applications Developer IV,NaN,H,SAR,NaN
23,180,NaN,Applications Developer V,NaN,H,SAR,NaN
24,NaN,NaN,1.1.2 Western Market,NaN,NaN,NaN,NaN
25,10,NaN,Senior Project Manager,NaN,H,SAR,NaN
26,20,NaN,IT Consultant,NaN,H,SAR,NaN
27,30,NaN,Integration & Architecture Consultant I,NaN,H,SAR,NaN
28,40,NaN,Functional Analyst I,NaN,H,SAR,NaN
29,50,NaN,Applications Developer I,NaN,H,SAR,NaN
30,60,NaN,Project Manager,NaN,H,SAR,NaN
31,70,NaN,Integration & Architecture Consultant II,NaN,H,SAR,NaN
32,80,NaN,Functional Analyst II,NaN,H,SAR,NaN
33,90,NaN,Applications Developer II,NaN,H,SAR,NaN
34,100,NaN,Integration & Arc. Consultant III,NaN,H,SAR,NaN
35,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
36,110,NaN,Change Management Consultant,NaN,H,SAR,NaN
37,120,NaN,Functional Analyst III,NaN,H,SAR,NaN
38,130,NaN,Applications Developer III,NaN,H,SAR,NaN
39,140,NaN,Training Development and Delivery,NaN,H,SAR,NaN
40,150,NaN,Technical Writer,NaN,H,SAR,NaN
41,160,NaN,Applications Developer IV,NaN,H,SAR,NaN
42,NaN,NaN,1.1.3 Eastern Market,NaN,NaN,NaN,NaN
43,10,NaN,Senior Project Manager,NaN,H,SAR,NaN
44,20,NaN,IT Consultant,NaN,H,SAR,NaN
45,30,NaN,Integration & Architecture Consultant I,NaN,H,SAR,NaN
46,40,NaN,Functional Analyst I,NaN,H,SAR,NaN
47,50,NaN,Applications Developer I,NaN,H,SAR,NaN
48,60,NaN,Project Manager,NaN,H,SAR,NaN
49,70,NaN,Integration & Architecture Consultant II,NaN,H,SAR,NaN
50,80,NaN,Functional Analyst II,NaN,H,SAR,NaN
51,90,NaN,Applications Developer II,NaN,H,SAR,NaN
52,100,NaN,Integration & Arc. Consultant III,NaN,H,SAR,NaN
53,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
54,110,NaN,Change Management Consultant,NaN,H,SAR,NaN
55,120,NaN,Functional Analyst III,NaN,H,SAR,NaN
56,130,NaN,Applications Developer III,NaN,H,SAR,NaN
57,140,NaN,Training Development and Delivery,NaN,H,SAR,NaN
58,150,NaN,Technical Writer,NaN,H,SAR,NaN
59,160,NaN,Applications Developer IV,NaN,H,SAR,NaN
60,NaN,NaN,1.2 Man-Day Rates,NaN,NaN,NaN,NaN
61,NaN,NaN,1.2.1 National Market,NaN,NaN,NaN,NaN
62,10,NaN,Senior Project Manager,NaN,DAY,SAR,NaN
63,20,NaN,IT Consultant,NaN,DAY,SAR,NaN
64,30,NaN,Integration & Architecture Consultant I,NaN,DAY,SAR,NaN
65,40,NaN,Functional Analyst I,NaN,DAY,SAR,NaN
66,50,NaN,Applications Developer I,NaN,DAY,SAR,NaN
67,60,NaN,Project Manager,NaN,DAY,SAR,NaN
68,70,NaN,Integration & Architecture Consultant II,NaN,DAY,SAR,NaN
69,80,NaN,Functional Analyst II,NaN,DAY,SAR,NaN
70,90,NaN,Applications Developer II,NaN,DAY,SAR,NaN
71,100,NaN,Integration & Arc. Consultant III,NaN,DAY,SAR,NaN
72,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
73,110,NaN,Change Management Consultant,NaN,DAY,SAR,NaN
74,120,NaN,Functional Analyst III,NaN,DAY,SAR,NaN
75,130,NaN,Applications Developer III,NaN,DAY,SAR,NaN
76,140,NaN,Training Development and Delivery,NaN,DAY,SAR,NaN
77,150,NaN,Technical Writer,NaN,DAY,SAR,NaN
78,160,NaN,Functional Analyst IV,NaN,DAY,SAR,NaN
79,170,NaN,Applications Developer IV,NaN,DAY,SAR,NaN
80,180,NaN,Applications Developer V,NaN,DAY,SAR,NaN
81,NaN,NaN,1.2.2 Western Market,NaN,NaN,NaN,NaN
82,10,NaN,Senior Project Manager,NaN,DAY,SAR,NaN
83,20,NaN,IT Consultant,NaN,DAY,SAR,NaN
84,30,NaN,Integration & Architecture Consultant I,NaN,DAY,SAR,NaN
85,40,NaN,Functional Analyst I,NaN,DAY,SAR,NaN
86,50,NaN,Applications Developer I,NaN,DAY,SAR,NaN
87,60,NaN,Project Manager,NaN,DAY,SAR,NaN
88,70,NaN,Integration & Architecture Consultant II,NaN,DAY,SAR,NaN
89,80,NaN,Functional Analyst II,NaN,DAY,SAR,NaN
90,90,NaN,Applications Developer II,NaN,DAY,SAR,NaN
91,100,NaN,Integration & Arc. Consultant III,NaN,DAY,SAR,NaN
92,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
93,110,NaN,Change Management Consultant,NaN,DAY,SAR,NaN
94,120,NaN,Functional Analyst III,NaN,DAY,SAR,NaN
95,130,NaN,Applications Developer III,NaN,DAY,SAR,NaN
96,140,NaN,Training Development and Delivery,NaN,DAY,SAR,NaN
97,150,NaN,Technical Writer,NaN,DAY,SAR,NaN
98,160,NaN,Applications Developer IV,NaN,DAY,SAR,NaN
99,NaN,NaN,1.2.3 Eastern Market,NaN,NaN,NaN,NaN
100,10,NaN,Senior Project Manager,NaN,DAY,SAR,NaN
101,20,NaN,IT Consultant,NaN,DAY,SAR,NaN
102,30,NaN,Integration & Architecture Consultant I,NaN,DAY,SAR,NaN
103,40,NaN,Functional Analyst I,NaN,DAY,SAR,NaN
104,50,NaN,Applications Developer I,NaN,DAY,SAR,NaN
105,60,NaN,Project Manager,NaN,DAY,SAR,NaN
106,70,NaN,Integration & Architecture Consultant II,NaN,DAY,SAR,NaN
107,80,NaN,Functional Analyst II,NaN,DAY,SAR,NaN
108,90,NaN,Applications Developer II,NaN,DAY,SAR,NaN
109,100,NaN,Integration & Arc. Consultant III,NaN,DAY,SAR,NaN
110,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
111,110,NaN,Change Management Consultant,NaN,DAY,SAR,NaN
112,120,NaN,Functional Analyst III,NaN,DAY,SAR,NaN
113,130,NaN,Applications Developer III,NaN,DAY,SAR,NaN
114,140,NaN,Training Development and Delivery,NaN,DAY,SAR,NaN
115,150,NaN,Technical Writer,NaN,DAY,SAR,NaN
116,160,NaN,Applications Developer IV,NaN,DAY,SAR,NaN
117,NaN,NaN,1.3 Man-Month Rates,NaN,NaN,NaN,NaN
118,NaN,NaN,1.3.1 National Market,NaN,NaN,NaN,NaN
119,10,NaN,Senior Project Manager,NaN,MON,SAR,NaN
120,20,NaN,IT Consultant,NaN,MON,SAR,NaN
121,30,NaN,Integration & Architecture Consultant I,NaN,MON,SAR,NaN
122,40,NaN,Functional Analyst I,NaN,MON,SAR,NaN
123,50,NaN,Applications Developer I,NaN,MON,SAR,NaN
124,60,NaN,Project Manager,NaN,MON,SAR,NaN
125,70,NaN,Integration & Architecture Consultant II,NaN,MON,SAR,NaN
126,80,NaN,Functional Analyst II,NaN,MON,SAR,NaN
127,90,NaN,Applications Developer II,NaN,MON,SAR,NaN
128,100,NaN,Integration & Arc. Consultant III,NaN,MON,SAR,NaN
129,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
130,110,NaN,Change Management Consultant,NaN,MON,SAR,NaN
131,120,NaN,Functional Analyst III,NaN,MON,SAR,NaN
132,130,NaN,Applications Developer III,NaN,MON,SAR,NaN
133,140,NaN,Training Development and Delivery,NaN,MON,SAR,NaN
134,150,NaN,Technical Writer,NaN,MON,SAR,NaN
135,160,NaN,Functional Analyst IV,NaN,MON,SAR,NaN
136,170,NaN,Applications Developer IV,NaN,MON,SAR,NaN
137,180,NaN,Applications Developer V,NaN,MON,SAR,NaN
138,NaN,NaN,1.3.2 Western Market,NaN,NaN,NaN,NaN
139,10,NaN,Senior Project Manager,NaN,MON,SAR,NaN
140,20,NaN,IT Consultant,NaN,MON,SAR,NaN
141,30,NaN,Integration & Architecture Consultant I,NaN,MON,SAR,NaN
142,40,NaN,Functional Analyst I,NaN,MON,SAR,NaN
143,50,NaN,Applications Developer I,NaN,MON,SAR,NaN
144,60,NaN,Project Manager,NaN,MON,SAR,NaN
145,70,NaN,Integration & Architecture Consultant II,NaN,MON,SAR,NaN
146,80,NaN,Functional Analyst II,NaN,MON,SAR,NaN
147,90,NaN,Applications Developer II,NaN,MON,SAR,NaN
148,100,NaN,Integration & Arc. Consultant III,NaN,MON,SAR,NaN
149,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
150,110,NaN,Change Management Consultant,NaN,MON,SAR,NaN
151,120,NaN,Functional Analyst III,NaN,MON,SAR,NaN
152,130,NaN,Applications Developer III,NaN,MON,SAR,NaN
153,140,NaN,Training Development and Delivery,NaN,MON,SAR,NaN
154,150,NaN,Technical Writer,NaN,MON,SAR,NaN
155,160,NaN,Applications Developer IV,NaN,MON,SAR,NaN
156,NaN,NaN,1.3.3 Eastern Market,NaN,NaN,NaN,NaN
157,10,NaN,Senior Project Manager,NaN,MON,SAR,NaN
158,20,NaN,IT Consultant,NaN,MON,SAR,NaN
159,30,NaN,Integration & Architecture Consultant I,NaN,MON,SAR,NaN
160,40,NaN,Functional Analyst I,NaN,MON,SAR,NaN
161,50,NaN,Applications Developer I,NaN,MON,SAR,NaN
162,60,NaN,Project Manager,NaN,MON,SAR,NaN
163,70,NaN,Integration & Architecture Consultant II,NaN,MON,SAR,NaN
164,80,NaN,Functional Analyst II,NaN,MON,SAR,NaN
165,90,NaN,Applications Developer II,NaN,MON,SAR,NaN
166,100,NaN,Integration & Arc. Consultant III,NaN,MON,SAR,NaN
167,NaN,NaN,Integration & Architecture Consultant III,NaN,NaN,NaN,NaN
168,110,NaN,Change Management Consultant,NaN,MON,SAR,NaN
169,120,NaN,Functional Analyst III,NaN,MON,SAR,NaN
170,130,NaN,Applications Developer III,NaN,MON,SAR,NaN
171,140,NaN,Training Development and Delivery,NaN,MON,SAR,NaN
172,150,NaN,Technical Writer,NaN,MON,SAR,NaN
173,160,NaN,Applications Developer IV,NaN,MON,SAR,NaN
174,NaN,NaN,2.0 SAUDI ARAMCO Project Team (PT) Office,NaN,NaN,NaN,NaN
175,10,NaN,As per Paragraph 12 of Schedule B,NaN,MON,SAR,NaN
176,NaN,NaN,3.0 Sponsorship Of Training & Certification,NaN,NaN,NaN,NaN
177,10,NaN,As per Paragraph 19 of Schedule H,NaN,VAL,SAR,NaN
178,NaN,NaN,Sponsorship Of Training & Certification For Co...,NaN,NaN,NaN,NaN
179,NaN,NaN,4.0 Agreed Liquidated Damages,NaN,NaN,NaN,NaN
180,10,NaN,AGREED LIQUIDATED DAMAGES,NaN,VAL,SAR,NaN
181,NaN,NaN,As per Paragarph 4 of Schedule H.,NaN,NaN,NaN,NaN
182,NaN,NaN,5.0 Saudization Penalty,NaN,NaN,NaN,NaN
183,10,NaN,Deduction Per Month,NaN,VAL,SAR,NaN
184,NaN,NaN,"Deduction of SR 20,000 per month for each empl...",NaN,NaN,NaN,NaN
185,NaN,NaN,required per Attachment I of Schedule S Paragr...,NaN,NaN,NaN,NaN
186,20,NaN,Deduction Per manhour,NaN,VAL,SAR,NaN
187,NaN,NaN,Deduction of SR100 for each Direct Labor manho...,NaN,NaN,NaN,NaN
188,NaN,NaN,required Saudization level as per Attachment I...,NaN,NaN,NaN,NaN
189,NaN,NaN,6.0 Lump Sum Release PO,NaN,NaN,NaN,NaN
190,10,NaN,Lump Sum Price,NaN,PU,SAR,NaN

In [15]:
# import re

# regex_pattern = r"^(?=[MDCLXVI])M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$"
# your_input = input('Please enter a roman numeral:')
# if re.match(regex_pattern, your_input, re.IGNORECASE):
#     print('YOur roman numeral was valid. Welcome.')
# else:
#     print('Invalid Roman Numeral')

In [16]:
# folder1 = {}

# for idx,i in enumerate(df1['Description']):
#     val = re.search(r'\b^((?=[MDCLXVI])M*(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3}))(\s|\S|)[a-zA-Z].+\b', i)

#     if val != None:
# #         print(val.group().strip())
        
# #         df2['ref_data'] = 
#         folder1[idx] = val.group().strip()
# #         print(idx, val.group())
        
# folder1

In [17]:
df1.fillna('',inplace = True, axis = 0)

In [18]:
df1

,Line_Item,Service_Number,Description,Quantity,Unit,CUR,Unit_Price
0,,,00001 IT Application Development & Implmnt.,,,,
1,10,,IT Application Development,,PU,SAR,
2,,,1.0 Time Unit Rates Release PO,,,,
3,,,1.1 Man-Hour Rates,,,,
4,,,1.1.1 National Market,,,,
5,10,,Senior Project Manager,,H,SAR,
6,20,,IT Consultant,,H,SAR,
7,30,,Integration & Architecture Consultant I,,H,SAR,
8,40,,Functional Analyst I,,H,SAR,
9,50,,Applications Developer I,,H,SAR,
10,60,,Project Manager,,H,SAR,
11,70,,Integration & Architecture Consultant II,,H,SAR,
12,80,,Functional Analyst II,,H,SAR,
13,90,,Applications Developer II,,H,SAR,
14,100,,Integration & Arc. Consultant III,,H,SAR,
15,,,Integration & Architecture Consultant III,,,,
16,110,,Change Management Consultant,,H,SAR,
17,120,,Functional Analyst III,,H,SAR,
18,130,,Applications Developer III,,H,SAR,
19,140,,Training Development and Delivery,,H,SAR,
20,150,,Technical Writer,,H,SAR,
21,160,,Functional Analyst IV,,H,SAR,
22,170,,Applications Developer IV,,H,SAR,
23,180,,Applications Developer V,,H,SAR,
24,,,1.1.2 Western Market,,,,
25,10,,Senior Project Manager,,H,SAR,
26,20,,IT Consultant,,H,SAR,
27,30,,Integration & Architecture Consultant I,,H,SAR,
28,40,,Functional Analyst I,,H,SAR,
29,50,,Applications Developer I,,H,SAR,
30,60,,Project Manager,,H,SAR,
31,70,,Integration & Architecture Consultant II,,H,SAR,
32,80,,Functional Analyst II,,H,SAR,
33,90,,Applications Developer II,,H,SAR,
34,100,,Integration & Arc. Consultant III,,H,SAR,
35,,,Integration & Architecture Consultant III,,,,
36,110,,Change Management Consultant,,H,SAR,
37,120,,Functional Analyst III,,H,SAR,
38,130,,Applications Developer III,,H,SAR,
39,140,,Training Development and Delivery,,H,SAR,
40,150,,Technical Writer,,H,SAR,
41,160,,Applications Developer IV,,H,SAR,
42,,,1.1.3 Eastern Market,,,,
43,10,,Senior Project Manager,,H,SAR,
44,20,,IT Consultant,,H,SAR,
45,30,,Integration & Architecture Consultant I,,H,SAR,
46,40,,Functional Analyst I,,H,SAR,
47,50,,Applications Developer I,,H,SAR,
48,60,,Project Manager,,H,SAR,
49,70,,Integration & Architecture Consultant II,,H,SAR,
50,80,,Functional Analyst II,,H,SAR,
51,90,,Applications Developer II,,H,SAR,
52,100,,Integration & Arc. Consultant III,,H,SAR,
53,,,Integration & Architecture Consultant III,,,,
54,110,,Change Management Consultant,,H,SAR,
55,120,,Functional Analyst III,,H,SAR,
56,130,,Applications Developer III,,H,SAR,
57,140,,Training Development and Delivery,,H,SAR,
58,150,,Technical Writer,,H,SAR,
59,160,,Applications Developer IV,,H,SAR,
60,,,1.2 Man-Day Rates,,,,
61,,,1.2.1 National Market,,,,
62,10,,Senior Project Manager,,DAY,SAR,
63,20,,IT Consultant,,DAY,SAR,
64,30,,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,Functional Analyst I,,DAY,SAR,
66,50,,Applications Developer I,,DAY,SAR,
67,60,,Project Manager,,DAY,SAR,
68,70,,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,Functional Analyst II,,DAY,SAR,
70,90,,Applications Developer II,,DAY,SAR,
71,100,,Integration & Arc. Consultant III,,DAY,SAR,
72,,,Integration & Architecture Consultant III,,,,
73,110,,Change Management Consultant,,DAY,SAR,
74,120,,Functional Analyst III,,DAY,SAR,
75,130,,Applications Developer III,,DAY,SAR,
76,140,,Training Development and Delivery,,DAY,SAR,
77,150,,Technical Writer,,DAY,SAR,
78,160,,Functional Analyst IV,,DAY,SAR,
79,170,,Applications Developer IV,,DAY,SAR,
80,180,,Applications Developer V,,DAY,SAR,
81,,,1.2.2 Western Market,,,,
82,10,,Senior Project Manager,,DAY,SAR,
83,20,,IT Consultant,,DAY,SAR,
84,30,,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,Functional Analyst I,,DAY,SAR,
86,50,,Applications Developer I,,DAY,SAR,
87,60,,Project Manager,,DAY,SAR,
88,70,,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,Functional Analyst II,,DAY,SAR,
90,90,,Applications Developer II,,DAY,SAR,
91,100,,Integration & Arc. Consultant III,,DAY,SAR,
92,,,Integration & Architecture Consultant III,,,,
93,110,,Change Management Consultant,,DAY,SAR,
94,120,,Functional Analyst III,,DAY,SAR,
95,130,,Applications Developer III,,DAY,SAR,
96,140,,Training Development and Delivery,,DAY,SAR,
97,150,,Technical Writer,,DAY,SAR,
98,160,,Applications Developer IV,,DAY,SAR,
99,,,1.2.3 Eastern Market,,,,
100,10,,Senior Project Manager,,DAY,SAR,
101,20,,IT Consultant,,DAY,SAR,
102,30,,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,Functional Analyst I,,DAY,SAR,
104,50,,Applications Developer I,,DAY,SAR,
105,60,,Project Manager,,DAY,SAR,
106,70,,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,Functional Analyst II,,DAY,SAR,
108,90,,Applications Developer II,,DAY,SAR,
109,100,,Integration & Arc. Consultant III,,DAY,SAR,
110,,,Integration & Architecture Consultant III,,,,
111,110,,Change Management Consultant,,DAY,SAR,
112,120,,Functional Analyst III,,DAY,SAR,
113,130,,Applications Developer III,,DAY,SAR,
114,140,,Training Development and Delivery,,DAY,SAR,
115,150,,Technical Writer,,DAY,SAR,
116,160,,Applications Developer IV,,DAY,SAR,
117,,,1.3 Man-Month Rates,,,,
118,,,1.3.1 National Market,,,,
119,10,,Senior Project Manager,,MON,SAR,
120,20,,IT Consultant,,MON,SAR,
121,30,,Integration & Architecture Consultant I,,MON,SAR,
122,40,,Functional Analyst I,,MON,SAR,
123,50,,Applications Developer I,,MON,SAR,
124,60,,Project Manager,,MON,SAR,
125,70,,Integration & Architecture Consultant II,,MON,SAR,
126,80,,Functional Analyst II,,MON,SAR,
127,90,,Applications Developer II,,MON,SAR,
128,100,,Integration & Arc. Consultant III,,MON,SAR,
129,,,Integration & Architecture Consultant III,,,,
130,110,,Change Management Consultant,,MON,SAR,
131,120,,Functional Analyst III,,MON,SAR,
132,130,,Applications Developer III,,MON,SAR,
133,140,,Training Development and Delivery,,MON,SAR,
134,150,,Technical Writer,,MON,SAR,
135,160,,Functional Analyst IV,,MON,SAR,
136,170,,Applications Developer IV,,MON,SAR,
137,180,,Applications Developer V,,MON,SAR,
138,,,1.3.2 Western Market,,,,
139,10,,Senior Project Manager,,MON,SAR,
140,20,,IT Consultant,,MON,SAR,
141,30,,Integration & Architecture Consultant I,,MON,SAR,
142,40,,Functional Analyst I,,MON,SAR,
143,50,,Applications Developer I,,MON,SAR,
144,60,,Project Manager,,MON,SAR,
145,70,,Integration & Architecture Consultant II,,MON,SAR,
146,80,,Functional Analyst II,,MON,SAR,
147,90,,Applications Developer II,,MON,SAR,
148,100,,Integration & Arc. Consultant III,,MON,SAR,
149,,,Integration & Architecture Consultant III,,,,
150,110,,Change Management Consultant,,MON,SAR,
151,120,,Functional Analyst III,,MON,SAR,
152,130,,Applications Developer III,,MON,SAR,
153,140,,Training Development and Delivery,,MON,SAR,
154,150,,Technical Writer,,MON,SAR,
155,160,,Applications Developer IV,,MON,SAR,
156,,,1.3.3 Eastern Market,,,,
157,10,,Senior Project Manager,,MON,SAR,
158,20,,IT Consultant,,MON,SAR,
159,30,,Integration & Architecture Consultant I,,MON,SAR,
160,40,,Functional Analyst I,,MON,SAR,
161,50,,Applications Developer I,,MON,SAR,
162,60,,Project Manager,,MON,SAR,
163,70,,Integration & Architecture Consultant II,,MON,SAR,
164,80,,Functional Analyst II,,MON,SAR,
165,90,,Applications Developer II,,MON,SAR,
166,100,,Integration & Arc. Consultant III,,MON,SAR,
167,,,Integration & Architecture Consultant III,,,,
168,110,,Change Management Consultant,,MON,SAR,
169,120,,Functional Analyst III,,MON,SAR,
170,130,,Applications Developer III,,MON,SAR,
171,140,,Training Development and Delivery,,MON,SAR,
172,150,,Technical Writer,,MON,SAR,
173,160,,Applications Developer IV,,MON,SAR,
174,,,2.0 SAUDI ARAMCO Project Team (PT) Office,,,,
175,10,,As per Paragraph 12 of Schedule B,,MON,SAR,
176,,,3.0 Sponsorship Of Training & Certification,,,,
177,10,,As per Paragraph 19 of Schedule H,,VAL,SAR,
178,,,Sponsorship Of Training & Certification For Co...,,,,
179,,,4.0 Agreed Liquidated Damages,,,,
180,10,,AGREED LIQUIDATED DAMAGES,,VAL,SAR,
181,,,As per Paragarph 4 of Schedule H.,,,,
182,,,5.0 Saudization Penalty,,,,
183,10,,Deduction Per Month,,VAL,SAR,
184,,,"Deduction of SR 20,000 per month for each empl...",,,,
185,,,required per Attachment I of Schedule S Paragr...,,,,
186,20,,Deduction Per manhour,,VAL,SAR,
187,,,Deduction of SR100 for each Direct Labor manho...,,,,
188,,,required Saudization level as per Attachment I...,,,,
189,,,6.0 Lump Sum Release PO,,,,
190,10,,Lump Sum Price,,PU,SAR,

In [19]:
df1.columns

Index(['Line_Item', 'Service_Number', 'Description', 'Quantity', 'Unit', 'CUR',
       'Unit_Price'],
      dtype='object')

In [20]:
# rr = pd.read_excel('alok_sample_09_09_22.xlsx', 'Reference')
# rr.columns

In [21]:
df1[:1]

,Line_Item,Service_Number,Description,Quantity,Unit,CUR,Unit_Price
0,,,00001 IT Application Development & Implmnt.,,,,

In [22]:
# rr[:1]

In [23]:
# df1.rename(columns = {'Line0AItem':'Contract Line Item'})

In [24]:
# df1.insert(0, 'SMR No', '')
# df1.insert(3, 'ERP No', '')
# df1.insert(5, 'File Name', '')
# df1.insert(2, 'RFQ_NO', df4['Unnamed: 2'][3])
# df1.insert(1, 'Requisition_No', df4['Unnamed: 2'][4])
# df1.insert(6, 'Folder_1', '')
# df1.insert(7, 'Folder_2', '')
# df1.insert(8, 'Folder_3', '')
# df1.insert(9, 'Folder De', '')

In [25]:
df1['Description'] = df1['Description'].apply(lambda x : x.strip())

In [26]:
df4

        Unnamed: 1  Unnamed: 2
3          RFQ No:  6000106938
4  Requisition No:  3000599798

In [27]:
df4['Unnamed: 2'][3]

6000106938

In [28]:
df1.insert(2, 'RFQ_NO', df4['Unnamed: 2'][3])
df1.insert(3, 'Requisition_No', df4['Unnamed: 2'][4])
df1.insert(4, 'Folder_1', '')
df1.insert(5, 'Folder_2', '')
df1.insert(6, 'Folder_3', '')

In [29]:
# df1[]

In [30]:
df1

,Line_Item,Service_Number,RFQ_NO,Requisition_No,Folder_1,Folder_2,Folder_3,Description,Quantity,Unit,CUR,Unit_Price
0,,,6000106938,3000599798,,,,00001 IT Application Development & Implmnt.,,,,
1,10,,6000106938,3000599798,,,,IT Application Development,,PU,SAR,
2,,,6000106938,3000599798,,,,1.0 Time Unit Rates Release PO,,,,
3,,,6000106938,3000599798,,,,1.1 Man-Hour Rates,,,,
4,,,6000106938,3000599798,,,,1.1.1 National Market,,,,
5,10,,6000106938,3000599798,,,,Senior Project Manager,,H,SAR,
6,20,,6000106938,3000599798,,,,IT Consultant,,H,SAR,
7,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,H,SAR,
8,40,,6000106938,3000599798,,,,Functional Analyst I,,H,SAR,
9,50,,6000106938,3000599798,,,,Applications Developer I,,H,SAR,
10,60,,6000106938,3000599798,,,,Project Manager,,H,SAR,
11,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,H,SAR,
12,80,,6000106938,3000599798,,,,Functional Analyst II,,H,SAR,
13,90,,6000106938,3000599798,,,,Applications Developer II,,H,SAR,
14,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,H,SAR,
15,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
16,110,,6000106938,3000599798,,,,Change Management Consultant,,H,SAR,
17,120,,6000106938,3000599798,,,,Functional Analyst III,,H,SAR,
18,130,,6000106938,3000599798,,,,Applications Developer III,,H,SAR,
19,140,,6000106938,3000599798,,,,Training Development and Delivery,,H,SAR,
20,150,,6000106938,3000599798,,,,Technical Writer,,H,SAR,
21,160,,6000106938,3000599798,,,,Functional Analyst IV,,H,SAR,
22,170,,6000106938,3000599798,,,,Applications Developer IV,,H,SAR,
23,180,,6000106938,3000599798,,,,Applications Developer V,,H,SAR,
24,,,6000106938,3000599798,,,,1.1.2 Western Market,,,,
25,10,,6000106938,3000599798,,,,Senior Project Manager,,H,SAR,
26,20,,6000106938,3000599798,,,,IT Consultant,,H,SAR,
27,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,H,SAR,
28,40,,6000106938,3000599798,,,,Functional Analyst I,,H,SAR,
29,50,,6000106938,3000599798,,,,Applications Developer I,,H,SAR,
30,60,,6000106938,3000599798,,,,Project Manager,,H,SAR,
31,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,H,SAR,
32,80,,6000106938,3000599798,,,,Functional Analyst II,,H,SAR,
33,90,,6000106938,3000599798,,,,Applications Developer II,,H,SAR,
34,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,H,SAR,
35,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
36,110,,6000106938,3000599798,,,,Change Management Consultant,,H,SAR,
37,120,,6000106938,3000599798,,,,Functional Analyst III,,H,SAR,
38,130,,6000106938,3000599798,,,,Applications Developer III,,H,SAR,
39,140,,6000106938,3000599798,,,,Training Development and Delivery,,H,SAR,
40,150,,6000106938,3000599798,,,,Technical Writer,,H,SAR,
41,160,,6000106938,3000599798,,,,Applications Developer IV,,H,SAR,
42,,,6000106938,3000599798,,,,1.1.3 Eastern Market,,,,
43,10,,6000106938,3000599798,,,,Senior Project Manager,,H,SAR,
44,20,,6000106938,3000599798,,,,IT Consultant,,H,SAR,
45,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,H,SAR,
46,40,,6000106938,3000599798,,,,Functional Analyst I,,H,SAR,
47,50,,6000106938,3000599798,,,,Applications Developer I,,H,SAR,
48,60,,6000106938,3000599798,,,,Project Manager,,H,SAR,
49,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,H,SAR,
50,80,,6000106938,3000599798,,,,Functional Analyst II,,H,SAR,
51,90,,6000106938,3000599798,,,,Applications Developer II,,H,SAR,
52,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,H,SAR,
53,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
54,110,,6000106938,3000599798,,,,Change Management Consultant,,H,SAR,
55,120,,6000106938,3000599798,,,,Functional Analyst III,,H,SAR,
56,130,,6000106938,3000599798,,,,Applications Developer III,,H,SAR,
57,140,,6000106938,3000599798,,,,Training Development and Delivery,,H,SAR,
58,150,,6000106938,3000599798,,,,Technical Writer,,H,SAR,
59,160,,6000106938,3000599798,,,,Applications Developer IV,,H,SAR,
60,,,6000106938,3000599798,,,,1.2 Man-Day Rates,,,,
61,,,6000106938,3000599798,,,,1.2.1 National Market,,,,
62,10,,6000106938,3000599798,,,,Senior Project Manager,,DAY,SAR,
63,20,,6000106938,3000599798,,,,IT Consultant,,DAY,SAR,
64,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,6000106938,3000599798,,,,Functional Analyst I,,DAY,SAR,
66,50,,6000106938,3000599798,,,,Applications Developer I,,DAY,SAR,
67,60,,6000106938,3000599798,,,,Project Manager,,DAY,SAR,
68,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,6000106938,3000599798,,,,Functional Analyst II,,DAY,SAR,
70,90,,6000106938,3000599798,,,,Applications Developer II,,DAY,SAR,
71,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,DAY,SAR,
72,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
73,110,,6000106938,3000599798,,,,Change Management Consultant,,DAY,SAR,
74,120,,6000106938,3000599798,,,,Functional Analyst III,,DAY,SAR,
75,130,,6000106938,3000599798,,,,Applications Developer III,,DAY,SAR,
76,140,,6000106938,3000599798,,,,Training Development and Delivery,,DAY,SAR,
77,150,,6000106938,3000599798,,,,Technical Writer,,DAY,SAR,
78,160,,6000106938,3000599798,,,,Functional Analyst IV,,DAY,SAR,
79,170,,6000106938,3000599798,,,,Applications Developer IV,,DAY,SAR,
80,180,,6000106938,3000599798,,,,Applications Developer V,,DAY,SAR,
81,,,6000106938,3000599798,,,,1.2.2 Western Market,,,,
82,10,,6000106938,3000599798,,,,Senior Project Manager,,DAY,SAR,
83,20,,6000106938,3000599798,,,,IT Consultant,,DAY,SAR,
84,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,6000106938,3000599798,,,,Functional Analyst I,,DAY,SAR,
86,50,,6000106938,3000599798,,,,Applications Developer I,,DAY,SAR,
87,60,,6000106938,3000599798,,,,Project Manager,,DAY,SAR,
88,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,6000106938,3000599798,,,,Functional Analyst II,,DAY,SAR,
90,90,,6000106938,3000599798,,,,Applications Developer II,,DAY,SAR,
91,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,DAY,SAR,
92,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
93,110,,6000106938,3000599798,,,,Change Management Consultant,,DAY,SAR,
94,120,,6000106938,3000599798,,,,Functional Analyst III,,DAY,SAR,
95,130,,6000106938,3000599798,,,,Applications Developer III,,DAY,SAR,
96,140,,6000106938,3000599798,,,,Training Development and Delivery,,DAY,SAR,
97,150,,6000106938,3000599798,,,,Technical Writer,,DAY,SAR,
98,160,,6000106938,3000599798,,,,Applications Developer IV,,DAY,SAR,
99,,,6000106938,3000599798,,,,1.2.3 Eastern Market,,,,
100,10,,6000106938,3000599798,,,,Senior Project Manager,,DAY,SAR,
101,20,,6000106938,3000599798,,,,IT Consultant,,DAY,SAR,
102,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,6000106938,3000599798,,,,Functional Analyst I,,DAY,SAR,
104,50,,6000106938,3000599798,,,,Applications Developer I,,DAY,SAR,
105,60,,6000106938,3000599798,,,,Project Manager,,DAY,SAR,
106,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,6000106938,3000599798,,,,Functional Analyst II,,DAY,SAR,
108,90,,6000106938,3000599798,,,,Applications Developer II,,DAY,SAR,
109,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,DAY,SAR,
110,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
111,110,,6000106938,3000599798,,,,Change Management Consultant,,DAY,SAR,
112,120,,6000106938,3000599798,,,,Functional Analyst III,,DAY,SAR,
113,130,,6000106938,3000599798,,,,Applications Developer III,,DAY,SAR,
114,140,,6000106938,3000599798,,,,Training Development and Delivery,,DAY,SAR,
115,150,,6000106938,3000599798,,,,Technical Writer,,DAY,SAR,
116,160,,6000106938,3000599798,,,,Applications Developer IV,,DAY,SAR,
117,,,6000106938,3000599798,,,,1.3 Man-Month Rates,,,,
118,,,6000106938,3000599798,,,,1.3.1 National Market,,,,
119,10,,6000106938,3000599798,,,,Senior Project Manager,,MON,SAR,
120,20,,6000106938,3000599798,,,,IT Consultant,,MON,SAR,
121,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,MON,SAR,
122,40,,6000106938,3000599798,,,,Functional Analyst I,,MON,SAR,
123,50,,6000106938,3000599798,,,,Applications Developer I,,MON,SAR,
124,60,,6000106938,3000599798,,,,Project Manager,,MON,SAR,
125,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,MON,SAR,
126,80,,6000106938,3000599798,,,,Functional Analyst II,,MON,SAR,
127,90,,6000106938,3000599798,,,,Applications Developer II,,MON,SAR,
128,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,MON,SAR,
129,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
130,110,,6000106938,3000599798,,,,Change Management Consultant,,MON,SAR,
131,120,,6000106938,3000599798,,,,Functional Analyst III,,MON,SAR,
132,130,,6000106938,3000599798,,,,Applications Developer III,,MON,SAR,
133,140,,6000106938,3000599798,,,,Training Development and Delivery,,MON,SAR,
134,150,,6000106938,3000599798,,,,Technical Writer,,MON,SAR,
135,160,,6000106938,3000599798,,,,Functional Analyst IV,,MON,SAR,
136,170,,6000106938,3000599798,,,,Applications Developer IV,,MON,SAR,
137,180,,6000106938,3000599798,,,,Applications Developer V,,MON,SAR,
138,,,6000106938,3000599798,,,,1.3.2 Western Market,,,,
139,10,,6000106938,3000599798,,,,Senior Project Manager,,MON,SAR,
140,20,,6000106938,3000599798,,,,IT Consultant,,MON,SAR,
141,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,MON,SAR,
142,40,,6000106938,3000599798,,,,Functional Analyst I,,MON,SAR,
143,50,,6000106938,3000599798,,,,Applications Developer I,,MON,SAR,
144,60,,6000106938,3000599798,,,,Project Manager,,MON,SAR,
145,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,MON,SAR,
146,80,,6000106938,3000599798,,,,Functional Analyst II,,MON,SAR,
147,90,,6000106938,3000599798,,,,Applications Developer II,,MON,SAR,
148,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,MON,SAR,
149,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
150,110,,6000106938,3000599798,,,,Change Management Consultant,,MON,SAR,
151,120,,6000106938,3000599798,,,,Functional Analyst III,,MON,SAR,
152,130,,6000106938,3000599798,,,,Applications Developer III,,MON,SAR,
153,140,,6000106938,3000599798,,,,Training Development and Delivery,,MON,SAR,
154,150,,6000106938,3000599798,,,,Technical Writer,,MON,SAR,
155,160,,6000106938,3000599798,,,,Applications Developer IV,,MON,SAR,
156,,,6000106938,3000599798,,,,1.3.3 Eastern Market,,,,
157,10,,6000106938,3000599798,,,,Senior Project Manager,,MON,SAR,
158,20,,6000106938,3000599798,,,,IT Consultant,,MON,SAR,
159,30,,6000106938,3000599798,,,,Integration & Architecture Consultant I,,MON,SAR,
160,40,,6000106938,3000599798,,,,Functional Analyst I,,MON,SAR,
161,50,,6000106938,3000599798,,,,Applications Developer I,,MON,SAR,
162,60,,6000106938,3000599798,,,,Project Manager,,MON,SAR,
163,70,,6000106938,3000599798,,,,Integration & Architecture Consultant II,,MON,SAR,
164,80,,6000106938,3000599798,,,,Functional Analyst II,,MON,SAR,
165,90,,6000106938,3000599798,,,,Applications Developer II,,MON,SAR,
166,100,,6000106938,3000599798,,,,Integration & Arc. Consultant III,,MON,SAR,
167,,,6000106938,3000599798,,,,Integration & Architecture Consultant III,,,,
168,110,,6000106938,3000599798,,,,Change Management Consultant,,MON,SAR,
169,120,,6000106938,3000599798,,,,Functional Analyst III,,MON,SAR,
170,130,,6000106938,3000599798,,,,Applications Developer III,,MON,SAR,
171,140,,6000106938,3000599798,,,,Training Development and Delivery,,MON,SAR,
172,150,,6000106938,3000599798,,,,Technical Writer,,MON,SAR,
173,160,,6000106938,3000599798,,,,Applications Developer IV,,MON,SAR,
174,,,6000106938,3000599798,,,,2.0 SAUDI ARAMCO Project Team (PT) Office,,,,
175,10,,6000106938,3000599798,,,,As per Paragraph 12 of Schedule B,,MON,SAR,
176,,,6000106938,3000599798,,,,3.0 Sponsorship Of Training & Certification,,,,
177,10,,6000106938,3000599798,,,,As per Paragraph 19 of Schedule H,,VAL,SAR,
178,,,6000106938,3000599798,,,,Sponsorship Of Training & Certification For Co...,,,,
179,,,6000106938,3000599798,,,,4.0 Agreed Liquidated Damages,,,,
180,10,,6000106938,3000599798,,,,AGREED LIQUIDATED DAMAGES,,VAL,SAR,
181,,,6000106938,3000599798,,,,As per Paragarph 4 of Schedule H.,,,,
182,,,6000106938,3000599798,,,,5.0 Saudization Penalty,,,,
183,10,,6000106938,3000599798,,,,Deduction Per Month,,VAL,SAR,
184,,,6000106938,3000599798,,,,"Deduction of SR 20,000 per month for each empl...",,,,
185,,,6000106938,3000599798,,,,required per Attachment I of Schedule S Paragr...,,,,
186,20,,6000106938,3000599798,,,,Deduction Per manhour,,VAL,SAR,
187,,,6000106938,3000599798,,,,Deduction of SR100 for each Direct Labor manho...,,,,
188,,,6000106938,3000599798,,,,required Saudization level as per Attachment I...,,,,
189,,,6000106938,3000599798,,,,6.0 Lump Sum Release PO,,,,
190,10,,6000106938,3000599798,,,,Lump Sum Price,,PU,SAR,

In [31]:
dic = {}

for idx,i in enumerate(df1['Description']):
    val = re.search(r'(^([0-9]{4,8}|[0-9]{1,2}[.][0-9]{1,2}|[0-9]{1}[.][0-9]{1}[.][0-9]{1}))(\s|\S|)[a-zA-Z].+', i)

    if val != None:
#         print(val.group().strip())
        
#         df2['ref_data'] = 
        dic[idx] = val.group().strip()
#         print(idx, val.group())
        
dic

{0: '00001 IT Application Development & Implmnt.',
 2: '1.0 Time Unit Rates Release PO',
 3: '1.1 Man-Hour Rates',
 4: '1.1.1 National Market',
 24: '1.1.2 Western Market',
 42: '1.1.3 Eastern Market',
 60: '1.2 Man-Day Rates',
 61: '1.2.1 National Market',
 81: '1.2.2 Western Market',
 99: '1.2.3 Eastern Market',
 117: '1.3 Man-Month Rates',
 118: '1.3.1 National Market',
 138: '1.3.2 Western Market',
 156: '1.3.3 Eastern Market',
 174: '2.0 SAUDI ARAMCO Project Team (PT) Office',
 176: '3.0 Sponsorship Of Training & Certification',
 179: '4.0 Agreed Liquidated Damages',
 182: '5.0 Saudization Penalty',
 189: '6.0 Lump Sum Release PO'}

In [32]:
data = pd.DataFrame(columns = ['key', 'value'])
data['key'] = dic.keys()
data['value'] = dic.values()
# data.to_excel('data.xlsx', index = False)
data

    key                                        value
0     0  00001 IT Application Development & Implmnt.
1     2               1.0 Time Unit Rates Release PO
2     3                           1.1 Man-Hour Rates
3     4                        1.1.1 National Market
4    24                         1.1.2 Western Market
5    42                         1.1.3 Eastern Market
6    60                            1.2 Man-Day Rates
7    61                        1.2.1 National Market
8    81                         1.2.2 Western Market
9    99                         1.2.3 Eastern Market
10  117                          1.3 Man-Month Rates
11  118                        1.3.1 National Market
12  138                         1.3.2 Western Market
13  156                         1.3.3 Eastern Market
14  174    2.0 SAUDI ARAMCO Project Team (PT) Office
15  176  3.0 Sponsorship Of Training & Certification
16  179                4.0 Agreed Liquidated Damages
17  182                      5.0 Saudization Penalty
18  189                      6.0 Lump Sum Release PO

In [33]:
folder1 = {}

for idx,i in enumerate(df1['Description']):
    val = re.search(r'(^([0-9]{4,8}|[0-9]{1,2}[.][0]{1,2}|[0-9]{1}[.][0]{1}))(\s|\S|)[a-zA-Z].+', i)

    if val != None:
#         print(val.group().strip())
        
#         df2['ref_data'] = 
        folder1[idx] = val.group().strip()
#         print(idx, val.group())
        
folder1

{0: '00001 IT Application Development & Implmnt.',
 2: '1.0 Time Unit Rates Release PO',
 174: '2.0 SAUDI ARAMCO Project Team (PT) Office',
 176: '3.0 Sponsorship Of Training & Certification',
 179: '4.0 Agreed Liquidated Damages',
 182: '5.0 Saudization Penalty',
 189: '6.0 Lump Sum Release PO'}

In [34]:
#     val = re.search(r'([0-9]{1,5}|[0-9]{1,3}[.][0-9]{1,3})(\s|\S)[a-zA-Z]{8,100}.+', i)

folder2 = {}

for idx,i in enumerate(df1['Description']):
    val = re.search(r'(^[0-9]{1,2}[.]([1-9]{1}[0-9]{1}|[1-9]{1}))(\s|\S|)[a-zA-Z].+', i)

    if val != None:
#         print(val.group().strip())
        
#         df2['ref_data'] = 
        folder2[idx] = val.group().strip()
#         print(idx, val.group())
        
folder2

{3: '1.1 Man-Hour Rates', 60: '1.2 Man-Day Rates', 117: '1.3 Man-Month Rates'}

In [35]:
#     val = re.search(r'([0-9]{1,5}|[0-9]{1,3}[.][0-9]{1,3})(\s|\S)[a-zA-Z]{8,100}.+', i)

folder3 = {}

for idx,i in enumerate(df1['Description']):
    val = re.search(r'(^[0-9]{1}[.][0-9]{1}[.][0-9]{1})(\s|\S|)[a-zA-Z].+', i)
#     print(i)
    if val != None:
#         print(val.group().strip())
        
#         df2['ref_data'] = 
        folder3[idx] = val.group().strip()
#         print(idx, val.group())
        
folder3

{4: '1.1.1 National Market',
 24: '1.1.2 Western Market',
 42: '1.1.3 Eastern Market',
 61: '1.2.1 National Market',
 81: '1.2.2 Western Market',
 99: '1.2.3 Eastern Market',
 118: '1.3.1 National Market',
 138: '1.3.2 Western Market',
 156: '1.3.3 Eastern Market'}

In [36]:
folder3

{4: '1.1.1 National Market',
 24: '1.1.2 Western Market',
 42: '1.1.3 Eastern Market',
 61: '1.2.1 National Market',
 81: '1.2.2 Western Market',
 99: '1.2.3 Eastern Market',
 118: '1.3.1 National Market',
 138: '1.3.2 Western Market',
 156: '1.3.3 Eastern Market'}

In [37]:
# lol = list(folder1.keys())
# lol1 = list(folder1.values())
# #         df1 = df1[lol[0]:lol[-1]+1]
# for i in range(len(lol)):
#     try:
#         df1['Folder_1'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
#     except IndexError:
#         df1['Folder_1'].iloc[range(lol[i] , len(df1))] = lol1[i]

In [38]:
# qq = list(folder1.keys())
# qq1 = (list(folder2.keys()))

# a = None

# for i in qq:
#     if i > qq1[-1]:
#         a = i
#         break

# lol = list(folder2.keys())
# lol1 = list(folder2.values())
# # df1 = df1[lol[0]:a]

# for i in range(len(lol)):
#     try:
#         df1['Folder_2'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
#     except IndexError:
#         df1['Folder_2'].iloc[range(lol[i] , a)] = lol1[i]

In [39]:
def value_insert(folder1, df1):

    if folder1:
        lol = list(folder1.keys())
        lol1 = list(folder1.values())
#         df1 = df1[lol[0]:lol[-1]+1]
        for i in range(len(lol)):
            try:
                df1['Folder_1'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
            except IndexError:
                df1['Folder_1'].iloc[range(lol[i] , len(df1))] = lol1[i]
    
#         elif folder3 == dic:
#             try:
#                 df1['Folder_3'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
#             except IndexError:
#                 df1['Folder_3'].iloc[range(lol[i] , len(df1))] = lol1[i]
            
    
    return df1

    #     print(lol[i] , lol[i+1])

In [40]:
if len(folder1) != 0:
    value_insert(folder1, df1)
else:
    print('Folder1 is Empty')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [41]:
df1

,Line_Item,Service_Number,RFQ_NO,Requisition_No,Folder_1,Folder_2,Folder_3,Description,Quantity,Unit,CUR,Unit_Price
0,,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,00001 IT Application Development & Implmnt.,,,,
1,10,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,IT Application Development,,PU,SAR,
2,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.0 Time Unit Rates Release PO,,,,
3,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.1 Man-Hour Rates,,,,
4,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.1.1 National Market,,,,
5,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,H,SAR,
6,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,H,SAR,
7,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,H,SAR,
8,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,H,SAR,
9,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,H,SAR,
10,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,H,SAR,
11,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,H,SAR,
12,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,H,SAR,
13,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,H,SAR,
14,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,H,SAR,
15,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
16,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,H,SAR,
17,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,H,SAR,
18,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,H,SAR,
19,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,H,SAR,
20,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,H,SAR,
21,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst IV,,H,SAR,
22,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,H,SAR,
23,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer V,,H,SAR,
24,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.1.2 Western Market,,,,
25,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,H,SAR,
26,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,H,SAR,
27,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,H,SAR,
28,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,H,SAR,
29,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,H,SAR,
30,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,H,SAR,
31,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,H,SAR,
32,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,H,SAR,
33,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,H,SAR,
34,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,H,SAR,
35,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
36,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,H,SAR,
37,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,H,SAR,
38,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,H,SAR,
39,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,H,SAR,
40,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,H,SAR,
41,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,H,SAR,
42,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.1.3 Eastern Market,,,,
43,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,H,SAR,
44,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,H,SAR,
45,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,H,SAR,
46,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,H,SAR,
47,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,H,SAR,
48,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,H,SAR,
49,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,H,SAR,
50,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,H,SAR,
51,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,H,SAR,
52,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,H,SAR,
53,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
54,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,H,SAR,
55,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,H,SAR,
56,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,H,SAR,
57,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,H,SAR,
58,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,H,SAR,
59,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,H,SAR,
60,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.2 Man-Day Rates,,,,
61,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.2.1 National Market,,,,
62,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,DAY,SAR,
63,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,DAY,SAR,
64,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,DAY,SAR,
66,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,DAY,SAR,
67,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,DAY,SAR,
68,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,DAY,SAR,
70,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,DAY,SAR,
71,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,DAY,SAR,
72,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
73,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,DAY,SAR,
74,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,DAY,SAR,
75,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,DAY,SAR,
76,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,DAY,SAR,
77,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,DAY,SAR,
78,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst IV,,DAY,SAR,
79,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,DAY,SAR,
80,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer V,,DAY,SAR,
81,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.2.2 Western Market,,,,
82,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,DAY,SAR,
83,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,DAY,SAR,
84,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,DAY,SAR,
86,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,DAY,SAR,
87,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,DAY,SAR,
88,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,DAY,SAR,
90,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,DAY,SAR,
91,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,DAY,SAR,
92,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
93,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,DAY,SAR,
94,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,DAY,SAR,
95,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,DAY,SAR,
96,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,DAY,SAR,
97,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,DAY,SAR,
98,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,DAY,SAR,
99,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.2.3 Eastern Market,,,,
100,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,DAY,SAR,
101,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,DAY,SAR,
102,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,DAY,SAR,
104,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,DAY,SAR,
105,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,DAY,SAR,
106,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,DAY,SAR,
108,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,DAY,SAR,
109,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,DAY,SAR,
110,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
111,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,DAY,SAR,
112,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,DAY,SAR,
113,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,DAY,SAR,
114,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,DAY,SAR,
115,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,DAY,SAR,
116,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,DAY,SAR,
117,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.3 Man-Month Rates,,,,
118,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.3.1 National Market,,,,
119,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,MON,SAR,
120,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,MON,SAR,
121,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,MON,SAR,
122,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,MON,SAR,
123,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,MON,SAR,
124,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,MON,SAR,
125,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,MON,SAR,
126,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,MON,SAR,
127,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,MON,SAR,
128,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,MON,SAR,
129,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
130,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,MON,SAR,
131,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,MON,SAR,
132,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,MON,SAR,
133,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,MON,SAR,
134,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,MON,SAR,
135,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst IV,,MON,SAR,
136,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,MON,SAR,
137,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer V,,MON,SAR,
138,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.3.2 Western Market,,,,
139,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,MON,SAR,
140,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,MON,SAR,
141,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,MON,SAR,
142,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,MON,SAR,
143,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,MON,SAR,
144,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,MON,SAR,
145,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,MON,SAR,
146,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,MON,SAR,
147,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,MON,SAR,
148,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,MON,SAR,
149,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
150,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,MON,SAR,
151,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,MON,SAR,
152,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,MON,SAR,
153,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,MON,SAR,
154,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,MON,SAR,
155,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,MON,SAR,
156,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.3.3 Eastern Market,,,,
157,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Senior Project Manager,,MON,SAR,
158,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,IT Consultant,,MON,SAR,
159,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant I,,MON,SAR,
160,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst I,,MON,SAR,
161,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer I,,MON,SAR,
162,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Project Manager,,MON,SAR,
163,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant II,,MON,SAR,
164,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst II,,MON,SAR,
165,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer II,,MON,SAR,
166,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Arc. Consultant III,,MON,SAR,
167,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Integration & Architecture Consultant III,,,,
168,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Change Management Consultant,,MON,SAR,
169,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Functional Analyst III,,MON,SAR,
170,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer III,,MON,SAR,
171,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Training Development and Delivery,,MON,SAR,
172,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Technical Writer,,MON,SAR,
173,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,Applications Developer IV,,MON,SAR,
174,,,6000106938,3000599798,2.0 SAUDI ARAMCO Project Team (PT) Office,,,2.0 SAUDI ARAMCO Project Team (PT) Office,,,,
175,10,,6000106938,3000599798,2.0 SAUDI ARAMCO Project Team (PT) Office,,,As per Paragraph 12 of Schedule B,,MON,SAR,
176,,,6000106938,3000599798,3.0 Sponsorship Of Training & Certification,,,3.0 Sponsorship Of Training & Certification,,,,
177,10,,6000106938,3000599798,3.0 Sponsorship Of Training & Certification,,,As per Paragraph 19 of Schedule H,,VAL,SAR,
178,,,6000106938,3000599798,3.0 Sponsorship Of Training & Certification,,,Sponsorship Of Training & Certification For Co...,,,,
179,,,6000106938,3000599798,4.0 Agreed Liquidated Damages,,,4.0 Agreed Liquidated Damages,,,,
180,10,,6000106938,3000599798,4.0 Agreed Liquidated Damages,,,AGREED LIQUIDATED DAMAGES,,VAL,SAR,
181,,,6000106938,3000599798,4.0 Agreed Liquidated Damages,,,As per Paragarph 4 of Schedule H.,,,,
182,,,6000106938,3000599798,5.0 Saudization Penalty,,,5.0 Saudization Penalty,,,,
183,10,,6000106938,3000599798,5.0 Saudization Penalty,,,Deduction Per Month,,VAL,SAR,
184,,,6000106938,3000599798,5.0 Saudization Penalty,,,"Deduction of SR 20,000 per month for each empl...",,,,
185,,,6000106938,3000599798,5.0 Saudization Penalty,,,required per Attachment I of Schedule S Paragr...,,,,
186,20,,6000106938,3000599798,5.0 Saudization Penalty,,,Deduction Per manhour,,VAL,SAR,
187,,,6000106938,3000599798,5.0 Saudization Penalty,,,Deduction of SR100 for each Direct Labor manho...,,,,
188,,,6000106938,3000599798,5.0 Saudization Penalty,,,required Saudization level as per Attachment I...,,,,
189,,,6000106938,3000599798,6.0 Lump Sum Release PO,,,6.0 Lump Sum Release PO,,,,
190,10,,6000106938,3000599798,6.0 Lump Sum Release PO,,,Lump Sum Price,,PU,SAR,

In [42]:
def value_insert1(folder1, folder2, df1):

    qq = list(folder1.keys())
    qq1 = (list(folder2.keys()))

    a = None

    for i in qq:
        if i > qq1[-1]:
            a = i
            break

    lol = list(folder2.keys())
    lol1 = list(folder2.values())
#         df1 = df1[lol[0]:a]
    print(a)
    for i in range(len(lol)):
        try:
            df1['Folder_2'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
        except IndexError:
            df1['Folder_2'].iloc[range(lol[i] , a)] = lol1[i]
    
    return df1

In [43]:
if ((len(folder1) != 0) and (len(folder2) != 0)):
    value_insert1(folder1, folder2, df1)
else:
    print('Folder2 is Empty')
df1

174

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

,Line_Item,Service_Number,RFQ_NO,Requisition_No,Folder_1,Folder_2,Folder_3,Description,Quantity,Unit,CUR,Unit_Price
0,,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,00001 IT Application Development & Implmnt.,,,,
1,10,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,IT Application Development,,PU,SAR,
2,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.0 Time Unit Rates Release PO,,,,
3,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1 Man-Hour Rates,,,,
4,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1.1 National Market,,,,
5,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Senior Project Manager,,H,SAR,
6,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,IT Consultant,,H,SAR,
7,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant I,,H,SAR,
8,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst I,,H,SAR,
9,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer I,,H,SAR,
10,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Project Manager,,H,SAR,
11,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant II,,H,SAR,
12,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst II,,H,SAR,
13,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer II,,H,SAR,
14,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Arc. Consultant III,,H,SAR,
15,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant III,,,,
16,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Change Management Consultant,,H,SAR,
17,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst III,,H,SAR,
18,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer III,,H,SAR,
19,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Training Development and Delivery,,H,SAR,
20,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Technical Writer,,H,SAR,
21,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst IV,,H,SAR,
22,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer IV,,H,SAR,
23,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer V,,H,SAR,
24,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1.2 Western Market,,,,
25,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Senior Project Manager,,H,SAR,
26,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,IT Consultant,,H,SAR,
27,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant I,,H,SAR,
28,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst I,,H,SAR,
29,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer I,,H,SAR,
30,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Project Manager,,H,SAR,
31,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant II,,H,SAR,
32,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst II,,H,SAR,
33,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer II,,H,SAR,
34,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Arc. Consultant III,,H,SAR,
35,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant III,,,,
36,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Change Management Consultant,,H,SAR,
37,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst III,,H,SAR,
38,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer III,,H,SAR,
39,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Training Development and Delivery,,H,SAR,
40,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Technical Writer,,H,SAR,
41,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer IV,,H,SAR,
42,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1.3 Eastern Market,,,,
43,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Senior Project Manager,,H,SAR,
44,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,IT Consultant,,H,SAR,
45,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant I,,H,SAR,
46,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst I,,H,SAR,
47,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer I,,H,SAR,
48,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Project Manager,,H,SAR,
49,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant II,,H,SAR,
50,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst II,,H,SAR,
51,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer II,,H,SAR,
52,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Arc. Consultant III,,H,SAR,
53,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Integration & Architecture Consultant III,,,,
54,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Change Management Consultant,,H,SAR,
55,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Functional Analyst III,,H,SAR,
56,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer III,,H,SAR,
57,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Training Development and Delivery,,H,SAR,
58,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Technical Writer,,H,SAR,
59,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,Applications Developer IV,,H,SAR,
60,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,1.2 Man-Day Rates,,,,
61,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,1.2.1 National Market,,,,
62,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Senior Project Manager,,DAY,SAR,
63,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,IT Consultant,,DAY,SAR,
64,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst I,,DAY,SAR,
66,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer I,,DAY,SAR,
67,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Project Manager,,DAY,SAR,
68,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst II,,DAY,SAR,
70,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer II,,DAY,SAR,
71,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Arc. Consultant III,,DAY,SAR,
72,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant III,,,,
73,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Change Management Consultant,,DAY,SAR,
74,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst III,,DAY,SAR,
75,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer III,,DAY,SAR,
76,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Training Development and Delivery,,DAY,SAR,
77,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Technical Writer,,DAY,SAR,
78,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst IV,,DAY,SAR,
79,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer IV,,DAY,SAR,
80,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer V,,DAY,SAR,
81,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,1.2.2 Western Market,,,,
82,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Senior Project Manager,,DAY,SAR,
83,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,IT Consultant,,DAY,SAR,
84,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst I,,DAY,SAR,
86,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer I,,DAY,SAR,
87,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Project Manager,,DAY,SAR,
88,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst II,,DAY,SAR,
90,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer II,,DAY,SAR,
91,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Arc. Consultant III,,DAY,SAR,
92,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant III,,,,
93,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Change Management Consultant,,DAY,SAR,
94,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst III,,DAY,SAR,
95,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer III,,DAY,SAR,
96,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Training Development and Delivery,,DAY,SAR,
97,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Technical Writer,,DAY,SAR,
98,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer IV,,DAY,SAR,
99,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,1.2.3 Eastern Market,,,,
100,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Senior Project Manager,,DAY,SAR,
101,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,IT Consultant,,DAY,SAR,
102,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst I,,DAY,SAR,
104,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer I,,DAY,SAR,
105,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Project Manager,,DAY,SAR,
106,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst II,,DAY,SAR,
108,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer II,,DAY,SAR,
109,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Arc. Consultant III,,DAY,SAR,
110,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Integration & Architecture Consultant III,,,,
111,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Change Management Consultant,,DAY,SAR,
112,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Functional Analyst III,,DAY,SAR,
113,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer III,,DAY,SAR,
114,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Training Development and Delivery,,DAY,SAR,
115,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Technical Writer,,DAY,SAR,
116,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,,Applications Developer IV,,DAY,SAR,
117,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,1.3 Man-Month Rates,,,,
118,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,1.3.1 National Market,,,,
119,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Senior Project Manager,,MON,SAR,
120,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,IT Consultant,,MON,SAR,
121,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant I,,MON,SAR,
122,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst I,,MON,SAR,
123,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer I,,MON,SAR,
124,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Project Manager,,MON,SAR,
125,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant II,,MON,SAR,
126,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst II,,MON,SAR,
127,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer II,,MON,SAR,
128,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Arc. Consultant III,,MON,SAR,
129,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant III,,,,
130,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Change Management Consultant,,MON,SAR,
131,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst III,,MON,SAR,
132,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer III,,MON,SAR,
133,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Training Development and Delivery,,MON,SAR,
134,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Technical Writer,,MON,SAR,
135,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst IV,,MON,SAR,
136,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer IV,,MON,SAR,
137,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer V,,MON,SAR,
138,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,1.3.2 Western Market,,,,
139,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Senior Project Manager,,MON,SAR,
140,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,IT Consultant,,MON,SAR,
141,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant I,,MON,SAR,
142,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst I,,MON,SAR,
143,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer I,,MON,SAR,
144,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Project Manager,,MON,SAR,
145,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant II,,MON,SAR,
146,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst II,,MON,SAR,
147,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer II,,MON,SAR,
148,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Arc. Consultant III,,MON,SAR,
149,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant III,,,,
150,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Change Management Consultant,,MON,SAR,
151,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst III,,MON,SAR,
152,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer III,,MON,SAR,
153,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Training Development and Delivery,,MON,SAR,
154,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Technical Writer,,MON,SAR,
155,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer IV,,MON,SAR,
156,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,1.3.3 Eastern Market,,,,
157,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Senior Project Manager,,MON,SAR,
158,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,IT Consultant,,MON,SAR,
159,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant I,,MON,SAR,
160,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst I,,MON,SAR,
161,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer I,,MON,SAR,
162,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Project Manager,,MON,SAR,
163,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant II,,MON,SAR,
164,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst II,,MON,SAR,
165,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer II,,MON,SAR,
166,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Arc. Consultant III,,MON,SAR,
167,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Integration & Architecture Consultant III,,,,
168,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Change Management Consultant,,MON,SAR,
169,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Functional Analyst III,,MON,SAR,
170,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Applications Developer III,,MON,SAR,
171,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,,Training Development and Delivery,,MON,SAR,

In [44]:
def value_insert2(folder1, folder3, df1):

    qq = list(folder1.keys())
    qq1 = (list(folder3.keys()))

    a = None

    for i in qq:
        if i > qq1[-1]:
            a = i
            break

    lol = list(folder3.keys())
    lol1 = list(folder3.values())
#         df1 = df1[lol[0]:a]

    for i in range(len(lol)):
        try:
            df1['Folder_3'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
        except IndexError:
            df1['Folder_3'].iloc[range(lol[i] , a)] = lol1[i]
    
    return df1

In [45]:
len(folder2) != 0

True

In [46]:
if ((len(folder1) != 0) and (len(folder3) != 0)):
    value_insert2(folder1, folder3, df1)
else:
    print('Folder3 is Empty')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [47]:
df1

,Line_Item,Service_Number,RFQ_NO,Requisition_No,Folder_1,Folder_2,Folder_3,Description,Quantity,Unit,CUR,Unit_Price
0,,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,00001 IT Application Development & Implmnt.,,,,
1,10,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,IT Application Development,,PU,SAR,
2,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.0 Time Unit Rates Release PO,,,,
3,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1 Man-Hour Rates,,,,
4,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,1.1.1 National Market,,,,
5,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Senior Project Manager,,H,SAR,
6,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,IT Consultant,,H,SAR,
7,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant I,,H,SAR,
8,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst I,,H,SAR,
9,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer I,,H,SAR,
10,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Project Manager,,H,SAR,
11,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant II,,H,SAR,
12,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst II,,H,SAR,
13,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer II,,H,SAR,
14,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Arc. Consultant III,,H,SAR,
15,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant III,,,,
16,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Change Management Consultant,,H,SAR,
17,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst III,,H,SAR,
18,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer III,,H,SAR,
19,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Training Development and Delivery,,H,SAR,
20,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Technical Writer,,H,SAR,
21,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst IV,,H,SAR,
22,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer IV,,H,SAR,
23,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer V,,H,SAR,
24,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,1.1.2 Western Market,,,,
25,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Senior Project Manager,,H,SAR,
26,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,IT Consultant,,H,SAR,
27,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant I,,H,SAR,
28,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst I,,H,SAR,
29,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer I,,H,SAR,
30,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Project Manager,,H,SAR,
31,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant II,,H,SAR,
32,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst II,,H,SAR,
33,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer II,,H,SAR,
34,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Arc. Consultant III,,H,SAR,
35,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant III,,,,
36,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Change Management Consultant,,H,SAR,
37,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst III,,H,SAR,
38,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer III,,H,SAR,
39,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Training Development and Delivery,,H,SAR,
40,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Technical Writer,,H,SAR,
41,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer IV,,H,SAR,
42,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,1.1.3 Eastern Market,,,,
43,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Senior Project Manager,,H,SAR,
44,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,IT Consultant,,H,SAR,
45,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant I,,H,SAR,
46,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst I,,H,SAR,
47,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer I,,H,SAR,
48,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Project Manager,,H,SAR,
49,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant II,,H,SAR,
50,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst II,,H,SAR,
51,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer II,,H,SAR,
52,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Arc. Consultant III,,H,SAR,
53,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant III,,,,
54,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Change Management Consultant,,H,SAR,
55,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst III,,H,SAR,
56,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer III,,H,SAR,
57,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Training Development and Delivery,,H,SAR,
58,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Technical Writer,,H,SAR,
59,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer IV,,H,SAR,
60,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.1.3 Eastern Market,1.2 Man-Day Rates,,,,
61,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,1.2.1 National Market,,,,
62,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Senior Project Manager,,DAY,SAR,
63,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,IT Consultant,,DAY,SAR,
64,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst I,,DAY,SAR,
66,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer I,,DAY,SAR,
67,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Project Manager,,DAY,SAR,
68,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst II,,DAY,SAR,
70,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer II,,DAY,SAR,
71,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Arc. Consultant III,,DAY,SAR,
72,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant III,,,,
73,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Change Management Consultant,,DAY,SAR,
74,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst III,,DAY,SAR,
75,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer III,,DAY,SAR,
76,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Training Development and Delivery,,DAY,SAR,
77,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Technical Writer,,DAY,SAR,
78,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst IV,,DAY,SAR,
79,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer IV,,DAY,SAR,
80,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer V,,DAY,SAR,
81,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,1.2.2 Western Market,,,,
82,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Senior Project Manager,,DAY,SAR,
83,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,IT Consultant,,DAY,SAR,
84,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst I,,DAY,SAR,
86,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer I,,DAY,SAR,
87,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Project Manager,,DAY,SAR,
88,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst II,,DAY,SAR,
90,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer II,,DAY,SAR,
91,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Arc. Consultant III,,DAY,SAR,
92,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant III,,,,
93,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Change Management Consultant,,DAY,SAR,
94,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst III,,DAY,SAR,
95,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer III,,DAY,SAR,
96,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Training Development and Delivery,,DAY,SAR,
97,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Technical Writer,,DAY,SAR,
98,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer IV,,DAY,SAR,
99,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,1.2.3 Eastern Market,,,,
100,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Senior Project Manager,,DAY,SAR,
101,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,IT Consultant,,DAY,SAR,
102,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst I,,DAY,SAR,
104,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer I,,DAY,SAR,
105,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Project Manager,,DAY,SAR,
106,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst II,,DAY,SAR,
108,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer II,,DAY,SAR,
109,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Arc. Consultant III,,DAY,SAR,
110,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant III,,,,
111,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Change Management Consultant,,DAY,SAR,
112,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst III,,DAY,SAR,
113,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer III,,DAY,SAR,
114,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Training Development and Delivery,,DAY,SAR,
115,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Technical Writer,,DAY,SAR,
116,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer IV,,DAY,SAR,
117,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.2.3 Eastern Market,1.3 Man-Month Rates,,,,
118,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,1.3.1 National Market,,,,
119,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Senior Project Manager,,MON,SAR,
120,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,IT Consultant,,MON,SAR,
121,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant I,,MON,SAR,
122,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst I,,MON,SAR,
123,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer I,,MON,SAR,
124,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Project Manager,,MON,SAR,
125,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant II,,MON,SAR,
126,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst II,,MON,SAR,
127,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer II,,MON,SAR,
128,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Arc. Consultant III,,MON,SAR,
129,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant III,,,,
130,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Change Management Consultant,,MON,SAR,
131,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst III,,MON,SAR,
132,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer III,,MON,SAR,
133,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Training Development and Delivery,,MON,SAR,
134,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Technical Writer,,MON,SAR,
135,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst IV,,MON,SAR,
136,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer IV,,MON,SAR,
137,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer V,,MON,SAR,
138,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,1.3.2 Western Market,,,,
139,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Senior Project Manager,,MON,SAR,
140,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,IT Consultant,,MON,SAR,
141,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Integration & Architecture Consultant I,,MON,SAR,
142,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Functional Analyst I,,MON,SAR,
143,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Applications Developer I,,MON,SAR,
144,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Project Manager,,MON,SAR,
145,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Integration & Architecture Consultant II,,MON,SAR,
146,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Functional Analyst II,,MON,SAR,

In [ ]:
# df1.drop(list(data.key.values))

In [49]:
data

    key                                        value
0     0  00001 IT Application Development & Implmnt.
1     2               1.0 Time Unit Rates Release PO
2     3                           1.1 Man-Hour Rates
3     4                        1.1.1 National Market
4    24                         1.1.2 Western Market
5    42                         1.1.3 Eastern Market
6    60                            1.2 Man-Day Rates
7    61                        1.2.1 National Market
8    81                         1.2.2 Western Market
9    99                         1.2.3 Eastern Market
10  117                          1.3 Man-Month Rates
11  118                        1.3.1 National Market
12  138                         1.3.2 Western Market
13  156                         1.3.3 Eastern Market
14  174    2.0 SAUDI ARAMCO Project Team (PT) Office
15  176  3.0 Sponsorship Of Training & Certification
16  179                4.0 Agreed Liquidated Damages
17  182                      5.0 Saudization Penalty
18  189                      6.0 Lump Sum Release PO

In [70]:
df1.columns

Index(['Line_Item', 'Service_Number', 'RFQ_NO', 'Requisition_No', 'Folder_1',
       'Folder_2', 'Folder_3', 'Description', 'Quantity', 'Unit', 'CUR',
       'Unit_Price'],
      dtype='object')

In [75]:
k = data.key.to_list()
for i in range(len(k[:1])):
    try:
#         print('try')
        df2 = (df1.iloc[range(k[i], k[i+1])])
    except:
#         print('exception index error')
        df2 = (df1.iloc[range(k[i], len(df1))])
#     print(df2)
#     print(len(df2))
    folder_des = ''
    short_des = ''
    long_des = ''
    for i in range(len(df2)):
        while df2['Line_Item'][i] == '':
            folder_des = ' '.join(df2['Description'][i])
            continue
        if df2['Line_Item'][i] != '':
            short_des = df2['Description'][i]

2

In [76]:
df1

,Line_Item,Service_Number,RFQ_NO,Requisition_No,Folder_1,Folder_2,Folder_3,Description,Quantity,Unit,CUR,Unit_Price
0,,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,00001 IT Application Development & Implmnt.,,,,
1,10,,6000106938,3000599798,00001 IT Application Development & Implmnt.,,,IT Application Development,,PU,SAR,
2,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,,,1.0 Time Unit Rates Release PO,,,,
3,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,,1.1 Man-Hour Rates,,,,
4,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,1.1.1 National Market,,,,
5,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Senior Project Manager,,H,SAR,
6,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,IT Consultant,,H,SAR,
7,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant I,,H,SAR,
8,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst I,,H,SAR,
9,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer I,,H,SAR,
10,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Project Manager,,H,SAR,
11,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant II,,H,SAR,
12,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst II,,H,SAR,
13,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer II,,H,SAR,
14,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Arc. Consultant III,,H,SAR,
15,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Integration & Architecture Consultant III,,,,
16,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Change Management Consultant,,H,SAR,
17,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst III,,H,SAR,
18,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer III,,H,SAR,
19,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Training Development and Delivery,,H,SAR,
20,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Technical Writer,,H,SAR,
21,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Functional Analyst IV,,H,SAR,
22,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer IV,,H,SAR,
23,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.1 National Market,Applications Developer V,,H,SAR,
24,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,1.1.2 Western Market,,,,
25,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Senior Project Manager,,H,SAR,
26,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,IT Consultant,,H,SAR,
27,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant I,,H,SAR,
28,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst I,,H,SAR,
29,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer I,,H,SAR,
30,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Project Manager,,H,SAR,
31,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant II,,H,SAR,
32,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst II,,H,SAR,
33,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer II,,H,SAR,
34,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Arc. Consultant III,,H,SAR,
35,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Integration & Architecture Consultant III,,,,
36,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Change Management Consultant,,H,SAR,
37,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Functional Analyst III,,H,SAR,
38,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer III,,H,SAR,
39,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Training Development and Delivery,,H,SAR,
40,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Technical Writer,,H,SAR,
41,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.2 Western Market,Applications Developer IV,,H,SAR,
42,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,1.1.3 Eastern Market,,,,
43,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Senior Project Manager,,H,SAR,
44,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,IT Consultant,,H,SAR,
45,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant I,,H,SAR,
46,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst I,,H,SAR,
47,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer I,,H,SAR,
48,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Project Manager,,H,SAR,
49,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant II,,H,SAR,
50,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst II,,H,SAR,
51,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer II,,H,SAR,
52,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Arc. Consultant III,,H,SAR,
53,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Integration & Architecture Consultant III,,,,
54,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Change Management Consultant,,H,SAR,
55,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Functional Analyst III,,H,SAR,
56,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer III,,H,SAR,
57,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Training Development and Delivery,,H,SAR,
58,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Technical Writer,,H,SAR,
59,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.1 Man-Hour Rates,1.1.3 Eastern Market,Applications Developer IV,,H,SAR,
60,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.1.3 Eastern Market,1.2 Man-Day Rates,,,,
61,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,1.2.1 National Market,,,,
62,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Senior Project Manager,,DAY,SAR,
63,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,IT Consultant,,DAY,SAR,
64,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant I,,DAY,SAR,
65,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst I,,DAY,SAR,
66,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer I,,DAY,SAR,
67,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Project Manager,,DAY,SAR,
68,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant II,,DAY,SAR,
69,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst II,,DAY,SAR,
70,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer II,,DAY,SAR,
71,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Arc. Consultant III,,DAY,SAR,
72,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Integration & Architecture Consultant III,,,,
73,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Change Management Consultant,,DAY,SAR,
74,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst III,,DAY,SAR,
75,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer III,,DAY,SAR,
76,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Training Development and Delivery,,DAY,SAR,
77,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Technical Writer,,DAY,SAR,
78,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Functional Analyst IV,,DAY,SAR,
79,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer IV,,DAY,SAR,
80,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.1 National Market,Applications Developer V,,DAY,SAR,
81,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,1.2.2 Western Market,,,,
82,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Senior Project Manager,,DAY,SAR,
83,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,IT Consultant,,DAY,SAR,
84,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant I,,DAY,SAR,
85,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst I,,DAY,SAR,
86,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer I,,DAY,SAR,
87,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Project Manager,,DAY,SAR,
88,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant II,,DAY,SAR,
89,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst II,,DAY,SAR,
90,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer II,,DAY,SAR,
91,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Arc. Consultant III,,DAY,SAR,
92,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Integration & Architecture Consultant III,,,,
93,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Change Management Consultant,,DAY,SAR,
94,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Functional Analyst III,,DAY,SAR,
95,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer III,,DAY,SAR,
96,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Training Development and Delivery,,DAY,SAR,
97,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Technical Writer,,DAY,SAR,
98,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.2 Western Market,Applications Developer IV,,DAY,SAR,
99,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,1.2.3 Eastern Market,,,,
100,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Senior Project Manager,,DAY,SAR,
101,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,IT Consultant,,DAY,SAR,
102,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant I,,DAY,SAR,
103,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst I,,DAY,SAR,
104,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer I,,DAY,SAR,
105,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Project Manager,,DAY,SAR,
106,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant II,,DAY,SAR,
107,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst II,,DAY,SAR,
108,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer II,,DAY,SAR,
109,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Arc. Consultant III,,DAY,SAR,
110,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Integration & Architecture Consultant III,,,,
111,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Change Management Consultant,,DAY,SAR,
112,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Functional Analyst III,,DAY,SAR,
113,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer III,,DAY,SAR,
114,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Training Development and Delivery,,DAY,SAR,
115,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Technical Writer,,DAY,SAR,
116,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.2 Man-Day Rates,1.2.3 Eastern Market,Applications Developer IV,,DAY,SAR,
117,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.2.3 Eastern Market,1.3 Man-Month Rates,,,,
118,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,1.3.1 National Market,,,,
119,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Senior Project Manager,,MON,SAR,
120,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,IT Consultant,,MON,SAR,
121,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant I,,MON,SAR,
122,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst I,,MON,SAR,
123,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer I,,MON,SAR,
124,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Project Manager,,MON,SAR,
125,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant II,,MON,SAR,
126,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst II,,MON,SAR,
127,90,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer II,,MON,SAR,
128,100,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Arc. Consultant III,,MON,SAR,
129,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Integration & Architecture Consultant III,,,,
130,110,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Change Management Consultant,,MON,SAR,
131,120,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst III,,MON,SAR,
132,130,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer III,,MON,SAR,
133,140,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Training Development and Delivery,,MON,SAR,
134,150,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Technical Writer,,MON,SAR,
135,160,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Functional Analyst IV,,MON,SAR,
136,170,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer IV,,MON,SAR,
137,180,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.1 National Market,Applications Developer V,,MON,SAR,
138,,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,1.3.2 Western Market,,,,
139,10,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Senior Project Manager,,MON,SAR,
140,20,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,IT Consultant,,MON,SAR,
141,30,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Integration & Architecture Consultant I,,MON,SAR,
142,40,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Functional Analyst I,,MON,SAR,
143,50,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Applications Developer I,,MON,SAR,
144,60,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Project Manager,,MON,SAR,
145,70,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Integration & Architecture Consultant II,,MON,SAR,
146,80,,6000106938,3000599798,1.0 Time Unit Rates Release PO,1.3 Man-Month Rates,1.3.2 Western Market,Functional Analyst II,,MON,SAR,

In [50]:
df3 = pd.DataFrame()

def sld_val(data, df1):
    k = data.key.to_list()
    for i in range(len(k)):
        df3 = df1.iloc[]

In [ ]:
for i in range(len(df1)):
    if df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '' and df1['Line_Item'][i+2] == '' and df1['Line_Item'][i+3] == '' and df1['Line_Item'][i+4] == '' and df1['Line_Item'][i+5] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1] + " " + df1['Description'][i+2]+ " " + df1['Description'][i+3]+ " " + df1['Description'][i+4]+ " " + df1['Description'][i+5]
        print(i, '6times')
    else:
        pass

In [ ]:
data.key.values.tolist()

In [ ]:
df1.drop(data.key.values.tolist(), axis = 0, inplace = True)

In [ ]:
df1.reset_index(drop = True, inplace = True)
df1

In [ ]:
df1.rename(columns = {'Line0AItem':'Line_Item'}, inplace=True)

In [ ]:
df1

In [ ]:
pp = df1[df1['Line_Item'] == '']
pp

In [ ]:
df1.insert(8, 'short_des', '')
df1.insert(9, 'long_des', '')

df1['short_des'] = df1['Description']
df1

In [ ]:
df1['Description'][169]

In [ ]:
# for i in range(len(df1)):
#     if df1['Line_Item'][i] == '':
#         df1['long_des'][i-1] = df

In [ ]:
# for i in range(len(df1)):
#     if df1['Line_Item'][i] == '':
#         df1['long_des'][i-1] = df1['Description'][i]

In [ ]:
df1['long_des'][165]

In [ ]:
# for i in range(len(df1)):
#     if df1['Line_Item'][i] == '':
#         df1['long_des'][i-1] = df1['Description'][i]

In [ ]:

for i in range(len(df1)):
    if df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '' and df1['Line_Item'][i+2] == '' and df1['Line_Item'][i+3] == '' and df1['Line_Item'][i+4] == '' and df1['Line_Item'][i+5] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1] + " " + df1['Description'][i+2]+ " " + df1['Description'][i+3]+ " " + df1['Description'][i+4]+ " " + df1['Description'][i+5]
        print(i, '6times')
    
    elif df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '' and df1['Line_Item'][i+2] == '' and df1['Line_Item'][i+3] == '' and df1['Line_Item'][i+4] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1] + " " + df1['Description'][i+2]+ " " + df1['Description'][i+3]+ " " + df1['Description'][i+4]
        print(i, '5times')
    
    elif df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '' and df1['Line_Item'][i+2] == '' and df1['Line_Item'][i+3] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1] + " " + df1['Description'][i+2]+ " " + df1['Description'][i+3]
        print(i, '4times')
        
    elif df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '' and df1['Line_Item'][i+2] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1] + " " + df1['Description'][i+2]
        print(i, '3times')
        
    elif df1['Line_Item'][i] == '' and df1['Line_Item'][i+1] == '':
        df1['long_des'][i-1] = df1['Description'][i] + " " + df1['Description'][i+1]
        print('2 times')
        
    elif df1['Line_Item'][i] == '':
        df1['long_des'][i-1] = df1['Description'][i]
        print("1time")
    else:
        pass
df1

In [ ]:
# data

In [ ]:
df1[1:8]

In [ ]:
df1[df1['Line_Item'] == ''].index.to_list()

In [ ]:
df1.drop(df1[df1['Line_Item'] == ''].index.to_list(), axis = 0, inplace = True)
df1.reset_index(drop = True, inplace = True)
df1

In [ ]:
df1.drop('Description', axis = 1, inplace = True)
df1

In [ ]:
# 156 + 15

In [ ]:
df1['long_des'] = np.where(df1['long_des'] == '', df1['short_des'], df1['long_des'])
df1

In [ ]:
import re
filename1 = re.sub('.xlsx|.xls', '', filename)
filename1

In [ ]:
df1.insert(4, "File Name", filename1)

In [ ]:
df1[:1]

In [ ]:
df1.columns

In [ ]:
df1 = df1[['Service_Number', 'Requisition_No','RFQ_NO', 'Line_Item','File Name',
       'Folder_1', 'Folder_2', 'Folder_3', 'short_des', 'long_des', 'Quantity',
       'Unit', 'CUR', 'Unit_Price', 'Per_UOM']]

In [ ]:
# df1[:1]

In [ ]:
# rr[:1]

In [ ]:
# rr = pd.read_excel('alok_sample_09_09_22.xlsx', 'Reference')
# rr.columns

In [ ]:
df1

In [ ]:
data

In [ ]:
df1['File Name'][0]

In [ ]:
df1.to_excel('3000190052-Schedule C - Pricing Attachment I_result.xlsx', index = False)

In [ ]:
df1['long_des'][168]

In [ ]:
for i in range(0, len(df1)):
    try:
        if ((df1['Line_Item'][i] == '' & df1['Line_Item'][i + 1] == '' )):
            print(df1['Line_Item'][i], df1['Line_Item'][i+1])
        else:
            print('hi')
    except:
        pass

In [ ]:
for i in range(len(df1)):

In [ ]:
df1['long_des'][165]

In [ ]:
df1[df1['Line_Item'] == '']

In [ ]:
df1

In [ ]:
df1.to_excel('aramco_12.09.22.xlsx', index = False)

In [ ]:
len(df1) + 19

In [ ]:
len(l)

In [ ]:
l = data.key.values.tolist()
l

In [ ]:
list(data.key.values())

In [ ]:
# ===============================================================================

In [ ]:
df1[:1]

In [ ]:
rr.columns

In [ ]:
folder3

In [ ]:
folder1

In [ ]:
w = list(folder1.keys())
ww1 = (list(folder3.keys()))
print(w)
print(ww1)

In [ ]:
def value_insert1(folder1, folder2, df1):

    qq = list(folder1.keys())
    qq1 = (list(folder2.keys()))

    a = None

    for i in qq:
        if i > qq1[-1]:
            a = i
            break

    lol = list(folder2.keys())
    lol1 = list(folder2.values())
#         df1 = df1[lol[0]:a]

    for i in range(len(lol)):
        try:
            df1['Folder_2'].iloc[range(lol[i] , lol[i+1])] = lol1[i]
        except IndexError:
            df1['Folder_2'].iloc[range(lol[i] , a)] = lol1[i]
    
    return df1

In [ ]:
lol1 = list(folder2.keys())
lol1

In [ ]:
folder3

In [ ]:
value_insert(folder1, df1)

In [ ]:
if folder3:
    lol = list(folder3.keys())
    lol1 = list(folder3.values())
#         df1 = df1[lol[0]:lol[-1]+1]
    for i in range(len(lol)):
        print(lol[i], lol[i+1])
#             df1['Folder_1'].iloc[range(lol[i] , lol[i+1])] = lol1[i]

In [ ]:
folder2

In [ ]:
data

In [ ]:
df1.iloc[range(lol1[0], lol1[-1]+1)] = 'lol'

In [ ]:
data

In [ ]:
folder1

In [ ]:
folder2

In [ ]:
qq = list(folder1.keys())
qq1 = (list(folder2.keys()))

a = None
for i in qq:
    if i > qq1[-1]:
        a = i
        break
a

In [ ]:
qq1

In [ ]:
for i in qq:
    if i > qq1[-1]:
        print(i)
        break

In [ ]:
qq3 = (list(folder3.keys()))
qq3

In [ ]:
for i in qq1:
    if i > qq3[-1]:
        print(i)
        break

In [ ]:
list(folder2.keys())

In [ ]:
print(lol, len(lol))
print(lol1, len(lol1))

In [ ]:
df1['Folder_1'].iloc[range(0,4)] = 'lol'

In [ ]:
data

In [ ]:
folder1

In [ ]:
lol[-1] + 1

In [ ]:
df3= df1[lol[0]:lol[-1] + 1]
df3

In [ ]:
df1[lol[0]:lol[-1] + 1]

In [ ]:
df1.iloc[range(lol[0], lol[-1] + 2)]